version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: data-simulate-db
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: